source("cachemean.R")
x <- 1:10
v <- makeVector(x)
cachemean(v)

source("cachematrix.R")
x <- matrix(1:9,3,3)
det(x)
v <- makeCacheMatrix(x)
cacheSolve(v)
x <- matrix(c(1,3,5,2,3,6,8,1,4),3,3)
det(x)
v <- makeCacheMatrix(x)
cacheSolve(v)
x <- matrix(c(1,0,5,2,1,6,3,4,0),3,3)
det(x)
v <- makeCacheMatrix(x)
cacheSolve(v)